services: 

  counter:
    image: aleman74/counter:latest

    environment: 
      - PORT=3001   
    volumes:
      - ./data:/data

  mongo:
    image: mongo
    container_name: d_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: db
#    ports:
#      - 27017:27017      
#    volumes:
#      - ./data/db:/data/db
#      - ./data/configdb:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: d_mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo


  book:
#    build:
#      context: .
#      dockerfile: Dockerfile  
#    image: aleman74/my_book:1.0.0
#    image: my_book:latest
    build: .

    ports: 
      - 80:3000
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3001/counter/
      - MONGO_URL=mongodb://root:example@mongo:27017
    depends_on:
      - counter
      - mongo

