services: 

  counter:
    image: aleman74/counter:latest

    environment: 
      - PORT=3001   
    volumes:
      - ./data:/data

  book:
    image: aleman74/my_book:1.0.0

    ports: 
      - 80:3000
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3001/counter/
    depends_on:
      - counter

